export { default as getTimestamp } from './getTimestamp'
export { default as getDocumentRef } from './getDocumentRef'
export { default as createDocument } from './createDocument'
export { default as deleteDocument } from './deleteDocument'
export { default as updateDocument } from './updateDocument'
export { default as getDocumentData } from './getDocumentData'
export { default as getCollectionRef } from './getCollectionRef'
export { default as getCollectionData } from './getCollectionData'
